default_language_version:
    python: python3.11
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: detect-private-key
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
          - id: check-yaml
          - id: check-toml
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black-jupyter
            language_version: python3.11
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            name: isort (python)
            args: [--profile, black]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.272
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
